# "ДВЕ  ЖИЗНИ", Часть I.  Том 1 (Original in Russian)



##Конкордия Евгеньевна  Антарова    (Кора)   

<p><em>Оккультый  роман,  весьма  популярный  в   кругу   людей,  интересующихся  идеями  Теософии    и   Учения  
Живой   Этики.  Герои   романа  —   великие души,   завершившие свою    духовную    эволюцию    на  Земле,  но  
оставшиеся  здесь,  чтобы   помогать    людям   в   их  духовном    восхождении.    По  свидетельству   автора  —  
известной    оперной     певицы,     ученицы     К.С.Станиславского,     солистки    Большого    театра  
К.Е.Антаровой    (1886–1959)     —   книга   писалась    ею  под     диктовку    и   была    начата  во  время   второй  
мировой войны.  
Книга    "Две    жизни"  записана    Конкордией  Евгеньевной     Антаровой   через   общение     с  
действительным   Автором     посредством     яснослышания    —   способом,   которым     записали    книги  
"Живой   Этики"  Е.И.Рерих   и   Н.К.Рерих,  "Тайную     Доктрину"   —   Е.П.Блаватская.     Единство  
Источника    этих    книг    вполне  очевидно    для     лиц,    их  прочитавших.    Учение,     изложенное  в   книгах  
"Живой   Этики",     как     бы  проиллюстрировано   судьбами    героев  книги   "Две    жизни".     Это     тот     же  
Источник    Единой  Истины, из  которого    вышли   Учения  Гаутамы Будды,  Иисуса  Христа  и   других  
Великих Учителей.  
Впервые  в   книге,  предназначенной     для     широкого    круга   читателей,  даются  яркие   и   глубокие  
Образы  Великих Учителей,   выписанные  с   огромной    любовью,    показан Их  самоотверженный труд    по  
раскрытию   Духа    человека.</em></p>

##Об    авторе   
<p>Перед   Вами,   читатель,   оккультный  роман,  который впервые выходит в  
свет     спустя  почти   35  лет     после   смерти  автора.     Он  принадлежит     перу  
К.Е.Антаровой,  одной   из  тех самоотверженных русских женщин, чья жизнь  
была    служением   красоте и   знанию.  
Кора    (Конкордия) Евгеньевна  Антарова    родилась    13  апреля  1886    года,   в  
то  счастливое  для творческих  натур   время,  когда   занимался   серебряный  век  
русской культуры.   А   природа щедро   наделила    её  талантами   —   в   том числе  
прекрасным  голосом,    контральто  редкого обаяния.    Поэтому одновременно  
с    занятиями   на  историко-филологическом     факультете  Высших  женских  
курсов  (знаменитых Бестужевских    курсов),    она оканчивает  Петербургскую  
консерваторию,  берёт   уроки   пения   у   И.  П.  Прянишникова    —   организатора  
и    руководителя    первого     в   России  оперного    товарищества;   в   1908    г.  её  
принимают   в   труппу  Большого    театра. На  этой    известной   всему   миру    сцене  
К.Е.    Антарова    проработала почти   тридцать    лет.  
Мы   можем   только  догадываться,   насколько   важную  роль    в   её  жизни  
сыграла  встреча     с   К.  С.  Станиславским:  в   течение     нескольких  лет     он  
преподавал  актёрское   мастерство  в   музыкальной студии  Большого    театра,  
ни   на  минуту  не  забывая     о   главной     своей   цели    —   расширять   сознание  
учеников,    пробуждая   в   них     духовность.     Прямое  свидетельство   тому    —  
книга    "Беседы     К.  С.  Станиславского  в   Студии  Большого    театра  в   1918–  
1922     гг.     Записаны    заслуженной     артисткой   РСФСР   К.Е.Антаровой".  
Конечно,     когда   молодая     ученица     гениального     режиссёра   от  раза    к   разу  
кропотливо   и   благоговейно    вела    стенографическую    запись  занятий,  
подготовив  потом   на  их  основе  книгу,  впервые увидевшую   свет    в   1939    г.  и  
выдержавшую несколько   изданий,    у   К.Е.Антаровой   не  было    ещё никаких  
артистических   званий. Но  она обладала    истинной    культурой   духа,   сердце  
имела    чистое  и   вдохновенное,   благодаря   чему    только  и   могла   стать  
учеником    в   подлинном   смысле  слова.  
Главные  действующие     лица    романа  "Две    жизни"  —   великие     души,  
завершившие  свою    духовную    эволюцию    на  Земле,  но  оставшиеся  здесь,  
чтобы    помогать    людям   в   их  духовном    восхождении,    —   пришли  к  
К.Е.Антаровой,   когда   бушевала    вторая  мировая     война,  и   этот    контакт  
продолжался многие  годы.  
К.Е.Антарова     умерла  в   1959    г.,     затем   рукопись    хранилась   у   Елены  
Федоровны    Тер-Арутюновой  (Москва),   считающей   её  своей   духовной</p>
<p>наставницей.    Хранительница   рукописи    никогда не  теряла  надежды увидеть  
роман   опубликованным, а   до  той поры    знакомила   с   ним всех,   кого    находила  
возможным.  И   потому  можно   сказать,    что этим    романом зачитывалось    уже  
не  одно    поколение   читателей.  
Мы   сердечно    благодарим  Е.Ф.Тер-Арутюнову,  которая     предоставила  
рукопись    романа  в   распоряжение    Латвийского общества    Рериха, за  доброе  
напутствие  книге,  начинающей  свою    новую   жизнь.</p>
 

